//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProIntegracao.Model.DetranSpWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aberturaAula", Namespace="http://schemas.datacontract.org/2004/07/ProIntegracao.WCF")]
    [System.SerializableAttribute()]
    public partial class aberturaAula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codCfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codCiretranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfInstrutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int erroCodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string erroDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeCandidatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroSerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtdAulasAbertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string renachField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codCf {
            get {
                return this.codCfField;
            }
            set {
                if ((object.ReferenceEquals(this.codCfField, value) != true)) {
                    this.codCfField = value;
                    this.RaisePropertyChanged("codCf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codCiretran {
            get {
                return this.codCiretranField;
            }
            set {
                if ((object.ReferenceEquals(this.codCiretranField, value) != true)) {
                    this.codCiretranField = value;
                    this.RaisePropertyChanged("codCiretran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpfInstrutor {
            get {
                return this.cpfInstrutorField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfInstrutorField, value) != true)) {
                    this.cpfInstrutorField = value;
                    this.RaisePropertyChanged("cpfInstrutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int erroCod {
            get {
                return this.erroCodField;
            }
            set {
                if ((this.erroCodField.Equals(value) != true)) {
                    this.erroCodField = value;
                    this.RaisePropertyChanged("erroCod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string erroDesc {
            get {
                return this.erroDescField;
            }
            set {
                if ((object.ReferenceEquals(this.erroDescField, value) != true)) {
                    this.erroDescField = value;
                    this.RaisePropertyChanged("erroDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                if ((object.ReferenceEquals(this.horaField, value) != true)) {
                    this.horaField = value;
                    this.RaisePropertyChanged("hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAula {
            get {
                return this.idAulaField;
            }
            set {
                if ((this.idAulaField.Equals(value) != true)) {
                    this.idAulaField = value;
                    this.RaisePropertyChanged("idAula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.mensagemField, value) != true)) {
                    this.mensagemField = value;
                    this.RaisePropertyChanged("mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeCandidato {
            get {
                return this.nomeCandidatoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeCandidatoField, value) != true)) {
                    this.nomeCandidatoField = value;
                    this.RaisePropertyChanged("nomeCandidato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroSerieField, value) != true)) {
                    this.numeroSerieField = value;
                    this.RaisePropertyChanged("numeroSerie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtdAulasAberta {
            get {
                return this.qtdAulasAbertaField;
            }
            set {
                if ((this.qtdAulasAbertaField.Equals(value) != true)) {
                    this.qtdAulasAbertaField = value;
                    this.RaisePropertyChanged("qtdAulasAberta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string renach {
            get {
                return this.renachField;
            }
            set {
                if ((object.ReferenceEquals(this.renachField, value) != true)) {
                    this.renachField = value;
                    this.RaisePropertyChanged("renach");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="erroDirecao", Namespace="http://schemas.datacontract.org/2004/07/ProIntegracao.WCF")]
    [System.SerializableAttribute()]
    public partial class erroDirecao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codErro {
            get {
                return this.codErroField;
            }
            set {
                if ((this.codErroField.Equals(value) != true)) {
                    this.codErroField = value;
                    this.RaisePropertyChanged("codErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                if ((this.quantidadeField.Equals(value) != true)) {
                    this.quantidadeField = value;
                    this.RaisePropertyChanged("quantidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="infracao", Namespace="http://schemas.datacontract.org/2004/07/ProIntegracao.WCF")]
    [System.SerializableAttribute()]
    public partial class infracao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string artigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long desdobramentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string artigo {
            get {
                return this.artigoField;
            }
            set {
                if ((object.ReferenceEquals(this.artigoField, value) != true)) {
                    this.artigoField = value;
                    this.RaisePropertyChanged("artigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long desdobramento {
            get {
                return this.desdobramentoField;
            }
            set {
                if ((this.desdobramentoField.Equals(value) != true)) {
                    this.desdobramentoField = value;
                    this.RaisePropertyChanged("desdobramento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                if ((this.quantidadeField.Equals(value) != true)) {
                    this.quantidadeField = value;
                    this.RaisePropertyChanged("quantidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fechamentoAula", Namespace="http://schemas.datacontract.org/2004/07/ProIntegracao.WCF")]
    [System.SerializableAttribute()]
    public partial class fechamentoAula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfInstrutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int erroCodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string erroDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idAulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroSerieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpfAluno {
            get {
                return this.cpfAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfAlunoField, value) != true)) {
                    this.cpfAlunoField = value;
                    this.RaisePropertyChanged("cpfAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpfInstrutor {
            get {
                return this.cpfInstrutorField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfInstrutorField, value) != true)) {
                    this.cpfInstrutorField = value;
                    this.RaisePropertyChanged("cpfInstrutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int erroCod {
            get {
                return this.erroCodField;
            }
            set {
                if ((this.erroCodField.Equals(value) != true)) {
                    this.erroCodField = value;
                    this.RaisePropertyChanged("erroCod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string erroDesc {
            get {
                return this.erroDescField;
            }
            set {
                if ((object.ReferenceEquals(this.erroDescField, value) != true)) {
                    this.erroDescField = value;
                    this.RaisePropertyChanged("erroDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idAula {
            get {
                return this.idAulaField;
            }
            set {
                if ((this.idAulaField.Equals(value) != true)) {
                    this.idAulaField = value;
                    this.RaisePropertyChanged("idAula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroSerieField, value) != true)) {
                    this.numeroSerieField = value;
                    this.RaisePropertyChanged("numeroSerie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="candidatoAulaSimulador", Namespace="http://schemas.datacontract.org/2004/07/ProIntegracao.WCF")]
    [System.SerializableAttribute()]
    public partial class candidatoAulaSimulador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codCfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codCiretranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long cpfAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int erroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string processoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string renachField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriaField, value) != true)) {
                    this.categoriaField = value;
                    this.RaisePropertyChanged("categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codCfc {
            get {
                return this.codCfcField;
            }
            set {
                if ((this.codCfcField.Equals(value) != true)) {
                    this.codCfcField = value;
                    this.RaisePropertyChanged("codCfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codCiretran {
            get {
                return this.codCiretranField;
            }
            set {
                if ((this.codCiretranField.Equals(value) != true)) {
                    this.codCiretranField = value;
                    this.RaisePropertyChanged("codCiretran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long cpfAluno {
            get {
                return this.cpfAlunoField;
            }
            set {
                if ((this.cpfAlunoField.Equals(value) != true)) {
                    this.cpfAlunoField = value;
                    this.RaisePropertyChanged("cpfAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descErro {
            get {
                return this.descErroField;
            }
            set {
                if ((object.ReferenceEquals(this.descErroField, value) != true)) {
                    this.descErroField = value;
                    this.RaisePropertyChanged("descErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int erro {
            get {
                return this.erroField;
            }
            set {
                if ((this.erroField.Equals(value) != true)) {
                    this.erroField = value;
                    this.RaisePropertyChanged("erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeAluno {
            get {
                return this.nomeAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeAlunoField, value) != true)) {
                    this.nomeAlunoField = value;
                    this.RaisePropertyChanged("nomeAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string processo {
            get {
                return this.processoField;
            }
            set {
                if ((object.ReferenceEquals(this.processoField, value) != true)) {
                    this.processoField = value;
                    this.RaisePropertyChanged("processo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string renach {
            get {
                return this.renachField;
            }
            set {
                if ((object.ReferenceEquals(this.renachField, value) != true)) {
                    this.renachField = value;
                    this.RaisePropertyChanged("renach");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AulaProdesp", Namespace="http://schemas.datacontract.org/2004/07/ProIntegracao.WCF")]
    [System.SerializableAttribute()]
    public partial class AulaProdesp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErroCodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long cpfAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfCancelamentoAulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horarioInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horarioTerminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusAulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErroCod {
            get {
                return this.ErroCodField;
            }
            set {
                if ((this.ErroCodField.Equals(value) != true)) {
                    this.ErroCodField = value;
                    this.RaisePropertyChanged("ErroCod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroDesc {
            get {
                return this.ErroDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroDescField, value) != true)) {
                    this.ErroDescField = value;
                    this.RaisePropertyChanged("ErroDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long cpfAluno {
            get {
                return this.cpfAlunoField;
            }
            set {
                if ((this.cpfAlunoField.Equals(value) != true)) {
                    this.cpfAlunoField = value;
                    this.RaisePropertyChanged("cpfAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpfCancelamentoAula {
            get {
                return this.cpfCancelamentoAulaField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfCancelamentoAulaField, value) != true)) {
                    this.cpfCancelamentoAulaField = value;
                    this.RaisePropertyChanged("cpfCancelamentoAula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horarioInicio {
            get {
                return this.horarioInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.horarioInicioField, value) != true)) {
                    this.horarioInicioField = value;
                    this.RaisePropertyChanged("horarioInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horarioTermino {
            get {
                return this.horarioTerminoField;
            }
            set {
                if ((object.ReferenceEquals(this.horarioTerminoField, value) != true)) {
                    this.horarioTerminoField = value;
                    this.RaisePropertyChanged("horarioTermino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAula {
            get {
                return this.idAulaField;
            }
            set {
                if ((this.idAulaField.Equals(value) != true)) {
                    this.idAulaField = value;
                    this.RaisePropertyChanged("idAula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusAula {
            get {
                return this.statusAulaField;
            }
            set {
                if ((object.ReferenceEquals(this.statusAulaField, value) != true)) {
                    this.statusAulaField = value;
                    this.RaisePropertyChanged("statusAula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DetranSpWS.ISimuladorService")]
    public interface ISimuladorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimuladorService/abrirAula", ReplyAction="http://tempuri.org/ISimuladorService/abrirAulaResponse")]
        ProIntegracao.Model.DetranSpWS.aberturaAula abrirAula(string cpfAluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimuladorService/fecharAula", ReplyAction="http://tempuri.org/ISimuladorService/fecharAulaResponse")]
        ProIntegracao.Model.DetranSpWS.fechamentoAula fecharAula(long Ticket, string Renach, int[] ModelosAula, int qtdeInfração, int qtdErroDirecao, ProIntegracao.Model.DetranSpWS.erroDirecao[] listErros, ProIntegracao.Model.DetranSpWS.infracao[] listInfracoes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimuladorService/InserirMatricula", ReplyAction="http://tempuri.org/ISimuladorService/InserirMatriculaResponse")]
        void InserirMatricula(string Nome, string Cpf, string Renachs, string DataNascimento, string Sexo, string Uf, string HoraAula, string PSA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimuladorService/consultarDadosAgendamento", ReplyAction="http://tempuri.org/ISimuladorService/consultarDadosAgendamentoResponse")]
        ProIntegracao.Model.DetranSpWS.candidatoAulaSimulador consultarDadosAgendamento(string cpfAluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimuladorService/consultarAula", ReplyAction="http://tempuri.org/ISimuladorService/consultarAulaResponse")]
        ProIntegracao.Model.DetranSpWS.AulaProdesp consultarAula(string cpf, long idAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimuladorService/consultarAulaCancelada", ReplyAction="http://tempuri.org/ISimuladorService/consultarAulaCanceladaResponse")]
        ProIntegracao.Model.DetranSpWS.AulaProdesp consultarAulaCancelada(string cpf, int idAula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimuladorServiceChannel : ProIntegracao.Model.DetranSpWS.ISimuladorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimuladorServiceClient : System.ServiceModel.ClientBase<ProIntegracao.Model.DetranSpWS.ISimuladorService>, ProIntegracao.Model.DetranSpWS.ISimuladorService {
        
        public SimuladorServiceClient() {
        }
        
        public SimuladorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimuladorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimuladorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimuladorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProIntegracao.Model.DetranSpWS.aberturaAula abrirAula(string cpfAluno) {
            return base.Channel.abrirAula(cpfAluno);
        }
        
        public ProIntegracao.Model.DetranSpWS.fechamentoAula fecharAula(long Ticket, string Renach, int[] ModelosAula, int qtdeInfração, int qtdErroDirecao, ProIntegracao.Model.DetranSpWS.erroDirecao[] listErros, ProIntegracao.Model.DetranSpWS.infracao[] listInfracoes) {
            return base.Channel.fecharAula(Ticket, Renach, ModelosAula, qtdeInfração, qtdErroDirecao, listErros, listInfracoes);
        }
        
        public void InserirMatricula(string Nome, string Cpf, string Renachs, string DataNascimento, string Sexo, string Uf, string HoraAula, string PSA) {
            base.Channel.InserirMatricula(Nome, Cpf, Renachs, DataNascimento, Sexo, Uf, HoraAula, PSA);
        }
        
        public ProIntegracao.Model.DetranSpWS.candidatoAulaSimulador consultarDadosAgendamento(string cpfAluno) {
            return base.Channel.consultarDadosAgendamento(cpfAluno);
        }
        
        public ProIntegracao.Model.DetranSpWS.AulaProdesp consultarAula(string cpf, long idAula) {
            return base.Channel.consultarAula(cpf, idAula);
        }
        
        public ProIntegracao.Model.DetranSpWS.AulaProdesp consultarAulaCancelada(string cpf, int idAula) {
            return base.Channel.consultarAulaCancelada(cpf, idAula);
        }
    }
}
