//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProIntegracao.Model.ReenvioAula {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReenvioAula.IReenvioAulaAutomatico")]
    public interface IReenvioAulaAutomatico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReenvioAulaAutomatico/ExecutarReenvio", ReplyAction="http://tempuri.org/IReenvioAulaAutomatico/ExecutarReenvioResponse")]
        void ExecutarReenvio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReenvioAulaAutomatico/EnvioAulaIntegracao", ReplyAction="http://tempuri.org/IReenvioAulaAutomatico/EnvioAulaIntegracaoResponse")]
        bool EnvioAulaIntegracao(int idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReenvioAulaAutomatico/CancelarAulaIntegracao", ReplyAction="http://tempuri.org/IReenvioAulaAutomatico/CancelarAulaIntegracaoResponse")]
        bool CancelarAulaIntegracao(int idAgenda);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReenvioAulaAutomaticoChannel : ProIntegracao.Model.ReenvioAula.IReenvioAulaAutomatico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReenvioAulaAutomaticoClient : System.ServiceModel.ClientBase<ProIntegracao.Model.ReenvioAula.IReenvioAulaAutomatico>, ProIntegracao.Model.ReenvioAula.IReenvioAulaAutomatico {
        
        public ReenvioAulaAutomaticoClient() {
        }
        
        public ReenvioAulaAutomaticoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReenvioAulaAutomaticoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReenvioAulaAutomaticoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReenvioAulaAutomaticoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ExecutarReenvio() {
            base.Channel.ExecutarReenvio();
        }
        
        public bool EnvioAulaIntegracao(int idAgenda) {
            return base.Channel.EnvioAulaIntegracao(idAgenda);
        }
        
        public bool CancelarAulaIntegracao(int idAgenda) {
            return base.Channel.CancelarAulaIntegracao(idAgenda);
        }
    }
}
